version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:

     - name: listing_id
       description: Primary key for the listing
       tests:
         - unique
         - not_null

     - name: host_id
       description: The host's id. Reference the host table.
       tests:
         - not_null
         - relationships:
             to: ref('dim_hosts_cleansed')
             field: host_id

     - name: room_type
       description: Type of the apartment / room
       tests:
         - accepted_values:
             values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
     - name: minimum_nights
       description: '{{doc("dim_listing_cleansed__minimum_nights")}}'
       tests:
         - positive_value    

  - name: dim_hosts_cleaned
    description: Cleaned host table of Airbnb
    columns:

      - name: host_id
        description: Host_id column of the airbnb
        tests:
         - not_null
         - unique

      - name: host_name
        description: The name of the host
        tests:
         - not_null

      - name: is_superhost
        description: Define whether the host is superhost or not 
        tests:
         - accepted_values:
              values: ['t','f']

     
     
